### ISSUE TITLE
Github Student Free development Accounts Heroku

### ISSUE THREAD

**Issue by pcwSlide** [heroku/roadmap#112]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

Node web app

### Tell us about what you're trying to solve. What challenges are you facing?

I and many others have written asking you to keep the previous free simple services as we use them for our students. You have devised the above but I cannot support this as I cannot mandate that a student hands over their card details. Make it as before - no card details required. PLUS - this should not be contingent on the student having to sign up with another service "GitHub Student Developer Pack "

**Comment by WolfgangFahl** [comment]
https://justpy-demo.herokuapp.com/ doesn't work any more and you end up getting an error message
```
at=error code=H14 desc="No web processes running"
```
which leads to https://stackoverflow.com/questions/41804507/h14-error-in-heroku-no-web-processes-running

justpy is an open source project with roughly 1000 stars and we do have a specific heroku tutorial
https://justpy.io/blog/heroku/

So basically we would be doing advertising for heroku if it would work. Why should we now paying for doing this advertising service instead of getting permanently supported by heroku for doing this advertising service?

Instead now the demo doesn't work and this looks as if heroku is broken and i assume has a negative impact on herokus business.

**Comment by friism** [comment]
@pcwSlide thanks for opening this issue. I understand that this is a painful change and I recognize and sympathize with the constraints you operate under as an educator. With that said, we're going to stick with the credit card requirement even for the GitHub program because it's the best approach we have for establishing user identities and reducing fraud and abuse of the service. The blog post announcing the changes [has more details](https://blog.heroku.com/next-chapter).

> Our product, engineering, and security teams are spending an extraordinary amount of effort to manage fraud and abuse of the Heroku free product plans

**Comment by WolfgangFahl** [comment]
Why did you close this without discussing the more general issue?

**Comment by friism** [comment]
@WolfgangFahl sorry about the pricing page snafu - can you please try to clear cookies and reload the page, that should make it work.

Re: open source project access to Heroku resources, that is actually something some of my colleagues are working on. I'll get back to you with resources once we have something ready.

**Comment by friism** [comment]
@WolfgangFahl also looks like we can use the other issue you created to track your suggestion: https://github.com/heroku/roadmap/issues/126
