### ISSUE TITLE
Heroku Research Program [We want your feedback!] 

### ISSUE THREAD

**Issue by ASayre** [heroku/roadmap#146]
We’re excited to announce the official launch of the [Heroku Research Program](https://uxresearch.my.salesforce-sites.com/ux/HerokuSourcing) to gather your thoughts on Heroku products and offerings!

The sign-up form can be found [here](https://uxresearch.my.salesforce-sites.com/ux/HerokuSourcing). Looking forward to your thoughts and ideas!

**Comment by friism** [comment]
@diwu1989 we updated the instance types around a year and a half ago, so they shouldn't be too dated: https://blog.heroku.com/faster-dynos-for-all

Changing to AMD-type instance instances is interesting, and we're loosely looking into Graviton-based instances too. At Heroku's scale, even changing from Intel to AMD-based instances is something we'd have to carefully test and consider since subsets of customers may rely on vendor-specific hardware extensions or accelerators (say for video encoding).

Thanks for reminding us to stay on top of instance-upgrades!

**Comment by raphjutras** [comment]
Do you plan of offering some more regions for Public /Common Runtime?

As a startup, we are unable to afford enterprise plans and will be compelled to move our infrastructure to a different provider because our clients require that their data be hosted in Canada due to laws. We absolutely LOVE Heroku for its simplicity and it will be a hassle to switch to another provider. However, we have no other option but to do so :(

Canada (Montreal) region will be vital to our company in the next year.

Do you plan on offering other regions to your smaller customers in a near future?
