### ISSUE TITLE
India: RBI compliant recurring payments

### ISSUE THREAD

**Issue by capeterson** [heroku/roadmap#17]
Heroku aims to be able to meet the Reserve Bank of India’s requirements on recurring payments and allow cardholders to create e-mandates through additional factor of authentication (AFA) using 3D Secure (3DS). This will allow us to transact in India by sending a pre-transaction notification to cardholders 24 hours in advance of any automated transaction, and allow all recurring transactions over INR 15,000 to go through AFA.

**Comment by Andser99** [comment]
Is it possible to enable this functionality for users from other countries? Since Heroku claims to increase their security and is client-driven this is a great feature that would solve many problems, unless the market model for Heroku is gaining money from people who forget to cancel a subscription, as is the case with all subscription models and the reason they exist in the first place.

Another proposal would be adding a one-time payment system for a predefined set of allocated resources.

**Comment by captn3m0** [comment]
Any progress on this front? This is still terribly broken.

**Comment by fluke** [comment]
Would be great to have a timeline on this.

**Comment by JorDaneeKey** [comment]
We have engineers actively working on major changes to our backend billing systems, including global support for 3D Secure 2.0 (3DS2), which would also make us compliant with updated banking rules for recurring payments in India. We're expecting to have this live in early 2023 at which point we could support credit card billing within India.

**Comment by vamsi** [comment]
Any progress on this issue?

**Comment by harshitx9** [comment]
@capeterson 
Heroku created a massive problem for Indian developers. Heroku billing gateway is not accepting Indian cards for individual customers. And given the 2023 timeline @JorDaneeKey informed, it is cruel that Heroku didn't think of the implications it would have. 

- Heroku created an incredible free cloud service for individual developers, which helped them to showcase their projects and much more.
- Since freebies can never be free forever(and shouldn't be as it is a liability for a company), Heroku decided to go premium for all.
- But before going all premium, Heroku must have found a way so that everyone can pay the bill to continue using the Heroku products. Instead, Heroku said they would not accept cards issued by Indian banks.
- Since 28th November is the last day for free dynos, many Indian developers will lose their live projects because of a payment issue.
- RBI compliance and Heroku carelessness will cause distrust.

You can never imagine how this would affect us. Let me give you some perspective.
I have college placements in the coming December, for which I gave my resume(having links to deployed projects on Heroku) to the placement office of my college. Through this process, different companies may offer me a job. But if the project in my resume will not work, it will adversely affect my chance of getting a job. Changing the already-submitted resume is impossible; otherwise, I would have used AWS or GCP.

I have many friends who have the same problem. A possible solution is that Heroku should extend the deadline to use free dynos for affected individual Indian users till it finds a payment solution. Otherwise, integrate a payment gateway with Heroku that can accept payments from Indian users before 28th November.

**Comment by manprajapat** [comment]
This is very sad to hear that, I am still waiting to activate the billing account. Can anyone confirm? My project is destroyed after 28 nov? Or still hope it is exists somewhere?

**Comment by JorDaneeKey** [comment]
@harsh-rajput-vats We hear you, and we are actively exploring solutions to enable our India customers as soon as possible, even something as simple as one-time payment solution through the dashboard instead of automatic debits.

**Comment by Prasanth777** [comment]
Do we have a timeline yet? I would love to come back to heroku instead of other services.

**Comment by manprajapat** [comment]
I can feel the pain of @harsh-rajput-vats. the main problem is that, I have shared my heroku links to my clients and somewhere their I can't change the URLs, I know I have code with me, but the Host Name is still not reachable, even if we want to pay it off. 
@JorDaneeKey please listen to us. This is only a payment gateway issue, that can be enable as per country law. Event AWS is running very much smoothly here.

**Comment by manishoctal** [comment]
Any update on this? This is really needed ASAP. ATLEAST THRY SHOULD START WITH PREPAID OPTION

**Comment by rtdp** [comment]
[JorDaneeKey](https://github.com/JorDaneeKey) Is there a one-time payment option now? At least I can pay my dues manually meanwhile to keep the projects going.

**Comment by manishoctal** [comment]
@rtdp I don't know, even they are listening to us. 
They are not accepting advanced payment. This is very ridiculous.

**Comment by friism** [comment]
We are listening! We're going to be picking up work to support 3DS, let me check on the details, but we should be able to move this to "working on it"

**Comment by timlaw17** [comment]
Hi all, happy to announce that we are moving this item to ’Working on It”. We will be utilizing 3DS to create the AFA mandates that will allow us to transact in India. This will also allow us to expand the security of 3DS2 to other regions.

**Comment by Mritunjay1121** [comment]
Please solve the issues , many of us had projects hosted there.

**Comment by TheInkWizard** [comment]
any updates on this?

**Comment by timlaw17** [comment]
@whyashthakker Rest assured that we are hard at work on implementing this functionality. We will share more as soon as we can, please keep an eye on this roadmap item.

**Comment by manprajapat** [comment]
This should be on high priority at least for your indian customers. They are waiting for your quick implementation atleast with Pre paid option to resume their work.

**Comment by rtdp** [comment]
I got a mail saying my app could be suspended on 19th April and I am not sure if there is a way to extend that or if should I invest in shifting away.

**Comment by manprajapat** [comment]
Seems, you guys are not listening customers seriosly, Still no updates on the progress!!

**Comment by Nagendra080389** [comment]
My account got permanently deleted because of this. The better approach would have been to keep the account frozen instead of deleting it.

**Comment by whyashthakker** [comment]
team any update on this?

**Comment by manishoctal** [comment]
Still waiting for the timeline? At Least please share the when we can get back on this?

**Comment by trackingtrail** [comment]
It's unbelievable how it's being neglected besides being a subsidiary of the biggest sales company, I cant even test my app for free without getting my card validated

**Comment by timlaw17** [comment]
Hi all,

I appreciate the activity on this roadmap item. The development of this functionality is in full swing. We aren't quite ready to share a timeline yet, but keep an eye on this work item for updates.

**Comment by Nagendra080389** [comment]
Hey @timlaw17 

Probably asking a wrong question to your team. But "My account got permanently deleted because of this. The better approach would have been to keep the account frozen instead of deleting it."

Anything which your or other team are doing about this? Or just deleting all our projects and years of work...

**Comment by timlaw17** [comment]
Hi @Nagendra080389,

I can't speak to your specific example, but I would point you to our CEO Bob Wise's [blog post where he addresses data deletion](https://blog.heroku.com/next-chapter): "Starting October 26, 2022, we will begin deleting inactive accounts and associated storage for accounts that have been inactive for over a year. Starting November 28, 2022, we plan to stop offering free product plans and plan to start shutting down free dynos and data services. We will be sending out a series of email communications to affected users."

If you have more specific questions relating to your account, I recommend reaching out to [https://heroku.support](https://heroku.support)

**Comment by Nagendra080389** [comment]
Yeah doesn't make any sense, as the account is inactive because i cannot pay for it, heroku stopped my payment as i am from india. And on the other hand that blog becomes illogical because its heroku which stopped the services, and not me.

**Comment by Mitrajeet-Golsangi** [comment]
> My account got permanently deleted because of this. The better approach would have been to keep the account frozen instead of deleting it.

I am facing the same issue, please update us on the updates as soon as possible.

**Comment by itsag** [comment]
I have been monitoring this thread for quite sometime now. It seems that the folks at Heroku have no plans of resuming their service for Indian customer any time soon. The best thing would be to start using a different provider like Netlify, Surge.sh, Cyclic, Railway, etc. It will definitely be cheaper.

✌️

**Comment by manprajapat** [comment]
Now, it seems, they are not listening to their customers. This is very unhappy thing for such big IT company. 
Atleast they can start pre payment service. I don't know what is the issue on that. Atleast we can start our services.

**Comment by timlaw17** [comment]
Hi all!

I am excited to announce that we are moving the roadmap item from In Progress to Coming Soon. Our development teams have been hard at work on bringing this functionality to our customers, and in accordance with our Coming Soon guidelines, we expect to deliver this functionality within the next month or two.

We will first enable 3D Secure 2 functionality in a small group of regions, before rolling it out to all users. When the roll out reaches India, we will support RBI e-mandates for recurring payments with both Visa and MasterCard credit cards. In the mean time, please continue to refer to this roadmap item for further updates. As we get closer to release, we will be sharing additional details here and on our [Heroku blog](https://blog.heroku.com/).

**Comment by anandsork** [comment]
Have anybody moved from Heroku to other providers? How was the experience? Which is a better one?
I had asked friend to add his CC assuming this will be supported.. However its hard to ask for favor for so many months.
Seems that Heroku is not getting much business from India & so just not entertaining.

**Comment by rtdp** [comment]
@anandsork if you running Rails, I have successfully shifted away apps to Cloud66 or Hatchbox with less effort. There are more similar competitors now.
About your question of not having much business from India - I feel they check their database and see not much business coming from India. But I think what they miss is businesses like mine - who have been using Heroku for more than 12 years now and recommending it to our clients. Even though our clients pay for Heroku from the USA, those got onto Heroku because of us. And we came to Heroku because its free tier and convenience. For the last 1 year, all of our new customers are on Heroku alternatives.

**Comment by manishoctal** [comment]
@timlaw17 Thanks for the update. we hope this timeline will not exceed. As we are a customer and we stuck.

**Comment by manishprajapatidev** [comment]
Hi @timlaw17 Any hope now? its being long time.

**Comment by vrj93** [comment]
Is this issue concerned with only Credit cards or Debit cards as well? My Card is being declined with the mention of incorrect details.

**Comment by timlaw17** [comment]
@manishprajapatidev We expect this to roll out in the next 1-2 months, we are getting close!

@vrj93 This issue affects both credit and debit cards issued from India financial institutions, we will accept both credit and debit cards once this functionality is released.

**Comment by vrj93** [comment]
> @manishprajapatidev We expect this to roll out in the next 1-2 months, we are getting close!
> 
> @vrj93 This issue affects both credit and debit cards issued from India financial institutions, we will accept both credit and debit cards once this functionality is released.

Thanks for the update. Does it mean there is no way to use the platform for new users like me?

**Comment by manishprajapatidev** [comment]
@timlaw17 OMG, again 1-2 months? Ahh

**Comment by timlaw17** [comment]
@manishprajapatidev Apologies for the confusion, I should clarify we are still on track for the 1-2 month window we initially posted when we moved this to "Coming Soon". There has been no delay.

**Comment by ranmax123** [comment]
Can we not delete assets and preserve them till this issue is resolved?

**Comment by timlaw17** [comment]
Hi all! We have taken the first step towards resuming our online business in India by enabling support for [3D Secure authentication](https://devcenter.heroku.com/changelog-items/2657). We are testing the India e-mandate functionality internally, and it should be rolling out within the next few weeks.

Keep an eye on this roadmap item for updates.

**Comment by vrj93** [comment]
Good to hear, thanks @timlaw17

**Comment by manishprajapatidev** [comment]
Very nice to see this. Today every indian customers are happy to see this.

**Comment by prem911** [comment]
First of all a big thanks to all behind this monumental progress to get back Indian Cards for payments. It has worked. Yay!!!

Note to all Indian users, only Visa and Mastercard cards are working. Rupay card was declined.
