### ISSUE TITLE
Official Cloud Native Buildpacks for Heroku languages

### ISSUE THREAD

**Issue by capeterson** [heroku/roadmap#19]
With the Heroku platform supporting Cloud Native Buildpacks as part of #20 , we will create officially supported CNBs for the following supported Ecosystems:

[Java/JVM](https://github.com/heroku/buildpacks-jvm)
[JavaScript & TypeScript/Node.js](https://github.com/heroku/buildpacks-nodejs)
[Python](https://github.com/heroku/buildpacks-python)
[Ruby](https://github.com/heroku/buildpacks-ruby)
[PHP](https://github.com/heroku/buildpacks-php)
[Go](https://github.com/heroku/buildpacks-go)

We have begun building these upon a common framework, [libcnb.rs](https://github.com/heroku/libcnb.rs) that we developed to provide an opinionated implementation of the CNB specification.

This is not intended to be a comprehensive list of buildpacks, and other Heroku-developed CNBs are also in various phases of experimentation.

We welcome your feedback and contributions!

**Comment by derekforeman** [comment]
An official .NET Core build pack would be great!

**Comment by earnold** [comment]
Hi Heroku 👋 

Per https://news.ycombinator.com/item?id=32594533#32595581
> Could you jump in on the cloud native buildpack issue above and ask for clarification? Goal of the public roadmap is to gather input and feedback and make it better

What's unclear to me is roughly...
* What is a Cloud Native Buildpack? 
* How is a cloud-native buildpack different from a regular one? 
* Also... why isn't "Cloud Native" hyphenated? 👅  (Seriously though... I find myself wondering, Is it a proper noun, like Docker? Or is a pattern, like 'serverless')
* How does this benefit me as a user of Heroku? What pain points go away? What new delights become available to me? 
* Why are the readme pages for the buildbacks so wildly different? For example, the python one is empty except for a link to brochure-ware, while the ruby one looks like it's the scribbled notes of a in-progress engineer. 

I hope that helps elucidate a long-time Heroku user's confusion. (I just plumbed my email - looks like I first registered for Heroku on Dec 21, 2009!)

**Comment by hone** [comment]
@earnold I can help. I helped co-create the original Buildpack API back in the day and co-founded Cloud Native Buildpacks.

> What is a Cloud Native Buildpack?
> How is a cloud-native buildpack different from a regular one?

Cloud Native Buildpacks (CNB) transform your application source code into a container image (OCI). Classic Heroku Buildpacks do a similar thing but produce slugs which are proprietary. Slugs aren't a widely accepted format. It also brings a bunch of other improvements of being able to leverage the existing tooling in the container space from the last half a decade. For instance, [`pack`](https://github.com/buildpacks/pack), a local CLI platform for CNB, will let you produce an OCI image that can be run locally or anywhere that supports a container image even Heroku's Container Runtime. This is something that you can't do easily with Classic Buildpacks.

If this has piqued your interest at all, I recommend you heading over to https://buildpacks.io to learn more.

> Also... why isn't "Cloud Native" hyphenated? tongue (Seriously though... I find myself wondering, Is it a proper noun, like Docker? Or is a pattern, like 'serverless')

I'm not sure, but I did help pick the name. We were trying to come up with the name for the next generation of Buildpacks. "Cloud Native" isn't always hyphenated from what we've found. The CNB project is part of the Cloud Native Computing Foundation (CNCF) as an incubation project, which does not hyphenate it.

> How does this benefit me as a user of Heroku? What pain points go away? What new delights become available to me?

The benefit to the Heroku user is CNB is about bringing containers to everyone. As I said above, I believe containers have made running production environments much simpler. It also makes your application even less "vendor locked-in", since the artifact produced can run in many places. I of course would prefer you to stay on Heroku. ;)

CNB is not just about re-implementing Heroku Classic Buildpacks onto containers, but it is its own vibrant OSS project that lives outside of Salesforce/Heroku. This was something that the Classic Buildpack project failed to achieve. This means we work with other companies interested in Buildpacks like VMware, Bloomberg, and RedHat to name a few. Some of the great things we've seen from this collaboration has been a push for things like [Software Bill of Materials which is on our roadmap](https://github.com/heroku/roadmap/issues/21) to provide customers.

> Why are the readme pages for the buildbacks so wildly different? For example, the python one is empty except for a link to brochure-ware, while the ruby one looks like it's the scribbled notes of a in-progress engineer.

The buildpacks are works in progress, which is why we have this roadmap item on here. :)

**Comment by hone** [comment]
> An official .NET Core build pack would be great!

@derekforeman please open an issue requesting it. :)
