### ISSUE TITLE
Sunsetting Deploy Hooks

### ISSUE THREAD

**Issue by afawcett** [heroku/roadmap#26]
Webhooks are a more secure, reliable, and powerful alternative to [Deploy Hooks](https://devcenter.heroku.com/articles/deploy-hooks), and five years ago, we made [app webhooks](https://blog.heroku.com/heroku-webhooks) Generally Available. Today, we are deprecating Deploy Hooks and encouraging customers to migrate to app webhooks.

More Information: https://blog.heroku.com/deployhooks-sunset

**Comment by motymichaely** [comment]
I loved [Deploy Hooks](https://devcenter.heroku.com/articles/deploy-hooks) and was using it extensively. Since it was lacking some features (I wanted to get notified on app changes other than deployments) I built the [Activity To Go](https://elements.heroku.com/addons/activitytogo) Heroku add-on as an alternative. Under the hood, and thanks to the great help of the Heroku team, it uses the secure and reliable webhooks infrastructure provided by Heroku. It can also be attached to multiple apps. 

I hope this helps Heroku users ease the sunset of Deploy Hooks.

More information: https://devcenter.heroku.com/articles/activitytogo

**Comment by afawcett** [comment]
Thanks for sharing @motymichaely

**Comment by motymichaely** [comment]
@afawcett - We just added a feature that provides the same event payload as Heroku deploy hooks, so it would make it way easier for Heroku deploy hook users to migrate with a minimal effort.

https://devcenter.heroku.com/articles/activitytogo#migrating-from-heroku-deploy-hooks

Hope this helps.

**Comment by afawcett** [comment]
Thanks for sharing @motymichaely with our customers - most useful.

**Comment by chrismarino** [comment]
Deploy hooks were sunsetted on Feb 28. Closing this issue.
