### ISSUE TITLE
[Hosting] [Education]: Educational Support

### ISSUE THREAD

**Issue by pcwSlide** [heroku/roadmap#44]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [X] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

Heroku

### Tell us about what you're trying to solve. What challenges are you facing?

```markdown
Many educators use Heroku, Mongo etc to introduce online concepts. I have assessments using these tools. Of course we can't compel students to use a  service that costs money.
Are you saying these accounts will be nullified 28-11-2022?
```

**Comment by pcwSlide** [comment]
Sad to comment on my own question - how long should it take to get an answer?

**Comment by claraj** [comment]
Also used Heroku free dynos for my students, both high school and college. The free tier with no credit card needed has been extremely useful and we've been graduating many, many Heroku fans for years 🙏 

The timing for the free dyno & PostgreSQL end is hard for educators since semesters tend to end mid-December. My curriculum for a fall semester has Heroku assessments through November and December, and the end is going to hit right in the middle of that.

So, knowing what the student plan will provide would be helpful. I know there's an announcement scheduled for the end of September but knowing sooner would help immensely. 

At the moment I don't know if we keep using our current Heroku assessments with minimal changes; or, do I need to find another host and create new assessments?  It's non-trivial to re-write assessments and the most lead time you can provide will help us teachers, our students, and future developers. 

Many thanks!

**Comment by pcwSlide** [comment]
Yes agreed - it's been 5 days and no reply. I, and many I suspect, will have to look elsewhere..

**Comment by capeterson** [comment]
Good feedback, especially on the semester timing. I'm reaching out to the folks working on the student plan to see if there's anything we can share here in the interim. 

I do want to ask specifically: are the schools in question legally classified as non-profits or public education? Or are you looking at education use cases that aren't within those specific categories? 

Anything else you can share about how you're using Heroku free would be helpful as well. I.e. are you using a team, or is each student just an individual account that's otherwise unassociated with each other? Which product(s) are you using? Presumably dynos and Postgres, but e.g. is Redis part of the picture in a meaningful way?

**Comment by pcwSlide** [comment]
Yes I work in the Higher education pubic sector. 

"are you using a team, or is each student just an individual account that's otherwise unassociated with each other? Which product(s) are you using? " - both..

All we are doing at he moment is Mongo for data  and Heroku to run the server - intro to working in the "cloud" space - Hybrid Apps. So it is a simple use case.

What I am hoping is that you can just leave our accounts till Christmas - this will give us time to migrate across to your new service structure in the new year. Thanks Phil..

**Comment by claraj** [comment]
> I'm reaching out to the folks working on the student plan to see if there's anything we can share here in the interim.

Great, thanks!

> I do want to ask specifically: are the schools in question legally classified as non-profits or public education? 

Yes - I'm at a state public community college, and we also serve PSEO students from our local public high schools.

> Anything else you can share about how you're using Heroku free would be helpful as well. I.e. are you using a team, or is each student just an individual account that's otherwise unassociated with each other? Which product(s) are you using? Presumably dynos and Postgres, but e.g. is Redis part of the picture in a meaningful way?

We are using individual accounts. Students are deploying Node and Python web apps using Heroku dynos, and Postgres.  I was planning to introduce Redis to classes next semester but, well, have to wait and see on that :)

I've also got a couple of APIs running on Heroku dynos that I've been using to introduce the concept of APIs; I also have an assignment grading app that uses Postgres and Redis. So hopefully educators will also be included in the student plans as well.

**Comment by pcwSlide** [comment]
> Sad to comment on my own question - how long should it take to get an answer?

Dear Mongo people - I have received your "6 new MongoDB product updates this September!" - very nice. However,
we have had no action on this request. When can we expect some information?

**Comment by friism** [comment]
Hey all, appreciate the input. I'm going to go ahead and close this issue. We announced Heroku's participation in the GitHub Student program: https://blog.heroku.com/github-student-developer-program

Also see the other issues related to Heroku use for students:

* https://github.com/heroku/roadmap/issues/18
* https://github.com/heroku/roadmap/issues/58

Please let me know if I missed something that's not captured on those.

**Comment by pcwSlide** [comment]
Just for the record,

As an educator I cannot in good conscious create content that forces a 
student to give their credit card details to a company. It is simply not 
ethical.

For our part, we will find another provider.

Phil
