### ISSUE TITLE
[service] [request]: free dynos and their worth for the free web

### ISSUE THREAD

**Issue by niccokunzmann** [heroku/roadmap#48]
### Required Terms

- [X] I agree to follow this project's [Code of Conduct](https://github.com/heroku/roadmap/blob/main/CODE_OF_CONDUCT.md)
- [ ] I have read and accept the [Salesforce Program Agreement](https://www.salesforce.com/company/program-agreement/)

### What service(s) is this request for?

Free Dynos and their contribution

### Tell us about what you're trying to solve. What challenges are you facing?

I was using Heroku for years now, embedding the Heroku Link into my free services hosted as open-source on GitHub.
The reason:
- These services are used only by a small number of people who I do not know
- I do not get any money for them
- I do not think that they should always run! I like that the dynos are switched off to save power!
- I use the free dynos of Heroku to test the deploy link.

What I need in order for people to try it out is a free hosting - then, they can decide if they like the FOSS software and deploy it themselves or if they want to use the free dynos.

I saw that the free dynos are switched off - and that in a line of other services like Travis and GitLab.com group size. I am worried about the accessibility and also Heroku's awareness of which role they play for the free software and open source ecosystem:

1. Open Source relies on accessibility for yet-to-empower/dis-empowered community members to form a huge base of diversity from which some projects excel. Heroku free dynos is a long-term reliable solution until now and I think, several main-stream understandings just want to crack down on free access.
2. On awareness: https://help.heroku.com/VF2KIQ5S/does-heroku-offer-non-profit-or-educational-discounts There seems to be no consideration for what these free dynos offer to the public. As soon as freedom is involved, maybe an exchange culture is not the right framework to reason in.

My proposal would be:
1. Think about in which position I am: I can not make Heroku do anything. Also, I know that free giving and supporting a diverse base on the web seems to be in a bit of a predicament. Maybe Heroku wants to go with the shift that I see that goes towards restricting what is freely available or narrow it down to those who have the money and not only the skill.
2. Please be sure that you want to support this decision! Are there statistics available on how much worth to the open web is generated through these free services? How much cost is involved?

So, I am not going to spend 35$ a month for the little improvements that I want to make to the free and open web and I wonder how you see it!
Is there anyone from what is now called "company responsibility/ethics" department here to give an understanding about the strategic considerations for the decision?

**Comment by sdnorris** [comment]
I would like to express my support for this message. As an artist who uses Heroku primarily for non-profit projects, I am very disappointed to see the free tier being so unceremoniously removed.  Many of the projects that I have done in the last few years were made possible only with free (albeit understandably limited) access to web hosting. Heroku's free tier is a genuinely radical and powerful service that enables experimentation on and with the web by individuals with otherwise limited access, and is responsible for advancing my own (and therefore probably also many others') understanding of how to develop for the internet. Removing it threatens the stability of the non-profit tier of web development, the ideas and members of which I am sure eventually feed into the functioning of the for-profit sector.
While the GM addresses this tangentially in this announcement in the "Students and Nonprofit Program," it does not address how individuals like myself, an artist and student not associated with an institution, be that academic or charitable, might be able to benefit from Heroku's ostensible "commitment to provide students with the resources and experiences they need to realize their potential."

**Comment by niccokunzmann** [comment]
> Removing it threatens the stability of the non-profit tier of web development, the ideas and members of which I am sure eventually feed into the functioning of the for-profit sector. - @sdnorris 

I would like to support this by example from my own software:
- [open-web-calendar](https://github.com/niccokunzmann/open-web-calendar/) is heroku hosted - free plan.
- [recurring-ical-events](https://pypi.org/project/recurring-ical-events/) is part of open-web-calendar and created as one of its parts. It has over 100k downloads per month.

**Comment by shiloh92** [comment]
Competitors will fill the 'free space'. All kinds of miniscule apps and services will find a new home elsewhere.

**Comment by Andser99** [comment]
> Competitors will fill the 'free space'. All kinds of miniscule apps and services will find a new home elsewhere.

I highly doubt that, as this is a global shift towards removing free services due to economical issues and an attempt to increase control over end-users since now - 
you have to pay for a dyno, thus giving your personal information.
you are tied to a specific platform for a given period of time.
even with all the promises a company can make, your data is at risk of being sold for advertisement.

**Comment by niccokunzmann** [comment]
> I highly doubt that, as this is a global shift towards removing free services due to economical issues and an attempt to increase control over end-users since now

I would like to know what the reasoning is. Maybe Heroku does not know that a huge number of projects embed a link to host their software on Heroku due to the fact that it is without initial cost. Maybe they calculated the numbers and take care of a vast number of stale projects and want to reduce the maintenance cost. Maybe, they have another strategy. Maybe, there is just little consideration due to a the possibility that free plan users are not integrated in the Heroku community. 

![image](https://user-images.githubusercontent.com/564768/187082839-4f260cd7-d8d9-42dd-afb9-ea2c9dd77c0d.png)

Above: picture of the embed button - they will fall away for new projects. - Yes they will because they can not be tested for free.

I doubt that I will migrate my projects fast nor will I migrate 100%. Also some of them are old and I moved on. I would like to have an overview over what exactly falls away. Heroku must have a list of URLs.

**Comment by savissimo** [comment]
> you have to pay for a dyno, thus giving your personal information

Not only that, but Heroku does not accept prepaid credit cards. While I understand the need to fight fraud attempts, prepaid cards are very common, and are considered marginally more secure for consumers (you may lose the money you put on them instead of your whole credit plafond). Personally, I have a credit card I never use and a prepaid credit card I use for online payments, but I could not use it for Heroku, not even for verification. This is another entry barrier that will make me go somewhere else.

**Comment by friism** [comment]
Thanks for opening this issue. Note that we subsequently announced new low cost plans that go some way to addressing some of your concerns: https://blog.heroku.com/new-low-cost-plans

Having worked on Heroku since 2013 (and similar services before then) I really do appreciate your comments about Heroku and it's importance for powering the free web. But as laid out in the [Next Chapter](https://blog.heroku.com/next-chapter#focus-on-mission-critical) blog post, it's incredibly painful to run any generally available service with access to even a modicum of "free" compute, which is why we made the decisions outlined in the post.
